### ISSUE TITLE
Sample project tabs not showing correctly.

### ISSUE THREAD

**Issue by vibesss** [EternityX/DEADCELL#4]
When using the sample project included, Tabs seem to be missing/out of bounds.

![tabs](https://user-images.githubusercontent.com/46655192/51089474-4f235f80-1733-11e9-8a2c-1837118f7371.PNG)

**Comment by EternityX** [comment]
This issue is fixed in commit 2637376c59860bd0e777fc48ce2c2dc82f9b0e87
